# Generated by Django 4.2.5 on 2023-10-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_history', models.JSONField(default=dict)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_delivery', models.CharField(choices=[('o', 'Обычная доставка'), ('e', 'Экспресс доставка')], default='o', max_length=1)),
                ('type_payment', models.CharField(choices=[('o', 'Онлайн картой'), ('r', 'Онлайн со случайного чужого счета')], default='o', max_length=1)),
                ('status', models.CharField(choices=[('p', 'Подтвержден'), ('o', 'Не подтвержден'), ('n', 'Отменен')], default='o', max_length=1)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('payment_error', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
